config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "books#home"

  devise_for :users, controllers: { sessions: "manager/sessions", passwords: "manager/passwords"}

  resources :room_messages
  resources :rooms, only: :create
  resources :books, only: [:index, :show]
  resources :orders, only: [:show, :new, :create]
  resources :carts, only: :update
  resources :categories, only: [:index, :show]
  resources :authors, only: [:index, :show]

  mount ActionCable.server => '/cable'

  namespace :manager do
    root "charts#index"

    resources :charts, only: :index do
      collection do
        get "revenue_in_month"
        get "revenue_in_year"
        get "select_to_year"
        get "compare_between_year"
      end
    end

    resources :chart_books, only: :index do
      collection do
        get "best_selling_books"
        get "best_selling_books_in_month"
        get "book_has_biggest_revenue"
        get "book_has_biggest_revenue_in_month"
      end
    end
    resources :rooms, only: [:index, :show]
  end

  post "/add_book", to: "carts#add_book"
end

app/views/shared/_flash.html.slim
- if flash[:alert]
  = js add_gritter(flash[:alert], title: "The Book Store", sticky: false, time: 1000)
- elsif flash[:error]
  = js add_gritter(flash[:error], title: "The Book Store", sticky: false, time: 1000)
- else
  = js add_gritter(flash[:notice], title: "The Book Store", sticky: false, time: 1000)

app/views/shared/_footer.html.slim
footer.footer
  .row
    .col-12
      p.footer__copyright = t "copyright"

app/views/shared/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top.row
  .container
    = link_to "Book Shop", root_path, class: "navbar-brand"
    button.navbar-toggler aria-controls="navbarResponsive" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarResponsive" data-toggle="collapse" type="button"
      span.navbar-toggler-icon
    #navbarResponsive.collapse.navbar-collapse
      ul.navbar-nav.ml-auto
        li class=("nav-item #{ active?(root_path) }")
          = link_to "Home", root_path, class: "nav-link"
        - if current_or_guest_user.admin?
          li class=("nav-item #{ active?(destroy_user_session_path) }")
            = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link"
        - else
          li class=("nav-item #{ active?(new_user_session_path) }")
            = link_to "Sign In", new_user_session_path, class: "nav-link"
          li class=("nav-item #{ active?(new_user_registration_path) }")
            = link_to "Sign Up", new_user_registration_path, class: "nav-link"

app/views/shared/_notification.html.slim
= link_to notify.content, order_path(notify.order.id), class: "dropdown-item #{ notify.status }"

app/views/shared/_order_detail.html.slim
li.shopping__item id="item_#{ detail.book.id }"

  = f.hidden_field :id, value: detail.id

  .shopping__count
    = f.number_field :quantity, { value: detail.quantity,
                                  min: 1,
                                  max: detail.book.quantity,
                                  step: 1,
                                  "data-price" =>  detail.book.price,
                                  class: "num_input" }
  p.shopping__description
    span.text_left
      = detail.book.name
    span.text_right
      i.fa.fa-trash.clickable data-id="#{detail.book.id}"
      = f.hidden_field :_destroy, value: false, id: "delete_item_#{detail.book.id}"
    span.text_right.price
      = number_to_currency(detail.price, precision: 0)

app/views/shared/_popup_chat.html.slim
.container
  .row
    = link_to rooms_path, method: :post, remote: true, class: "btn btn-primary", id: "addClass"
      i.fab.fa-facebook-messenger

#qnimate.popup-box.chat-popup
  .popup-head
    button#removeClass.chat-header-button.pull-right data-widget="remove" type="button"
      i.far.fa-times-circle
  .popup-messages#messages
  .popup-messages-footer#popup-form

app/views/shared/_side_bar.html.slim
- if categories
  h3 = t "category"
  .sidebar
    ul.sidebar__list
      - categories.each do |category|
        li
          = link_to category_path(category), class: "sidebar__link" do
            .sidebar__data
              h4.sidebar__name = category.name
    - unless current_page?(categories_path)
      .sidebar__pages
        = button_to categories_path, method: "get", class: "btn-inline" do
          = t("all_category")

- if authors
  h3 = t "authors"
  .sidebar
    ul.sidebar__list
      - authors.each do |author|
        li
          = link_to author_path(author), class: "sidebar__link" do
            .sidebar__data
              h4.sidebar__name = author.name
    - unless current_page?(authors_path)
      .sidebar__pages
        = button_to authors_path, method: "get", class: "btn-inline" do
          = t("all_authors")