config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "books#home"

  devise_for :users, controllers: { sessions: "manager/sessions", passwords: "manager/passwords"}

  resources :room_messages
  resources :rooms, only: :create
  resources :books, only: [:index, :show]
  resources :orders, only: [:show, :new, :create]
  resources :carts, only: :update
  resources :categories, only: [:index, :show]
  resources :authors, only: [:index, :show]

  mount ActionCable.server => '/cable'

  namespace :manager do
    root "charts#index"

    resources :charts, only: :index do
      collection do
        get "revenue_in_month"
        get "revenue_in_year"
        get "select_to_year"
        get "compare_between_year"
      end
    end

    resources :chart_books, only: :index do
      collection do
        get "best_selling_books"
        get "best_selling_books_in_month"
        get "book_has_biggest_revenue"
        get "book_has_biggest_revenue_in_month"
      end
    end
    resources :rooms, only: [:index, :show]
  end

  post "/add_book", to: "carts#add_book"
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  enum status: { opening: 0, closed: 1 }

  belongs_to :assignee, class_name: "User", optional: true
  belongs_to :guest, class_name: "User"
  has_many :room_messages

  validates :name, presence: true, uniqueness: true

  def assign_to_admin
    User.select_assignee.assigned_rooms << self
    room_messages.create!(message: I18n.t("greeting"), user_id: assignee_id)
  end

  def update_on_send_message(user)
    room_messages.unprocessed.update_all(status: :processed) if user.admin?
  end

  class << self
    def close_guest_room(guest_id)
      guest_room = find_by(guest_id: guest_id)
      guest_room.closed!
      RoomBroadcastJob.perform_later(guest_room)
    end
  end
end

app/controllers/manager/rooms_controller.rb
# frozen_string_literal: true

module Manager
  class RoomsController < BaseController
    before_action :load_room, only: :show

    def index
      @rooms = current_user.assigned_rooms.opening
    end

    def show
      respond_to do |format|
        format.js
      end
    end

    private

    def load_room
      @room = Room.find(params[:id])
    end
  end
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  def create
    @room = Room.find_or_create_by(name: "Room #{guest_user.email}", guest_id: guest_user.id)
    respond_to do |format|
      format.js
    end
  end
end

app/views/rooms/_room.html.slim
.msg_history#messages data-room-id="#{ room.id }" data-user-id="#{ current_or_guest_user.id }"
  = render partial: "room_messages/room_message", collection: room.room_messages,
    as: :room_message, locals: { current_user_id: current_or_guest_user.id }
= render "room_messages/message_form", room: room

app/views/rooms/_rooms_list.html.slim
- if room.opening? && room.guest
  = link_to room_path(room), id: "room_#{room.id}", remote: true do
    div class="chat_list #{ room.room_messages.last.status }" id="item_#{ room.id }"
      .chat_people
        .chat_img
          = image_tag "user-profile.png"
        .chat_ib.font-weight-bold
          h5
            = "Guest #{ room.guest.id }"
            span.chat_date
              = I18n.l(room.room_messages.last.created_at, format: :short)
          p
            = room.room_messages.last.message

app/views/rooms/create.js.slim
- if @room.errors.any?
  | alert("#{@room}");
- else
  | $('#messages').html("#{ j render @room.room_messages, current_user_id: current_or_guest_user.id }");
  | $('#messages').attr("data-room-id", #{ @room.id });
  | $('#messages').attr("data-user-id", #{ current_or_guest_user.id });
  | $('#popup-form').html("#{ j render "room_messages/message_form", room: @room }");
  | CreateRoomChanel();
  | CreateApperanceChanel();