config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "books#home"

  devise_for :users, controllers: { sessions: "manager/sessions", passwords: "manager/passwords"}

  resources :room_messages
  resources :rooms, only: :create
  resources :books, only: [:index, :show]
  resources :orders, only: [:show, :new, :create]
  resources :carts, only: :update
  resources :categories, only: [:index, :show]
  resources :authors, only: [:index, :show]

  mount ActionCable.server => '/cable'

  namespace :manager do
    root "charts#index"

    resources :charts, only: :index do
      collection do
        get "revenue_in_month"
        get "revenue_in_year"
        get "select_to_year"
        get "compare_between_year"
      end
    end

    resources :chart_books, only: :index do
      collection do
        get "best_selling_books"
        get "best_selling_books_in_month"
        get "book_has_biggest_revenue"
        get "book_has_biggest_revenue_in_month"
      end
    end
    resources :rooms, only: [:index, :show]
  end

  post "/add_book", to: "carts#add_book"
end

app/controllers/manager/base_controller.rb
# frozen_string_literal: true

module Manager
  class BaseController < ApplicationController
    layout "manager"
    before_action :authenticate_user!
  end
end

app/controllers/manager/chart_books_controller.rb
# frozen_string_literal: true

module Manager
  class ChartBooksController < BaseController
    include MonthConcern

    def index
      @year = Order.pluck(Arel.sql("DISTINCT YEAR(created_at)")).sort.reverse
    end

    def best_selling_books
      render json: Order.best_sell_book_in_year(params[:year]).to_h
    end

    def best_selling_books_in_month
      month = revenue_month_default
      list_book = Order.best_selling_books_the_month_in_year(params[:year], params[:book]).to_h
      render json: month.merge(list_book)
    end

    def book_has_biggest_revenue
      months = Order.where("YEAR(created_at) = ?", params[:year])
                    .pluck(Arel.sql("DISTINCT MONTH(created_at)")).sort
      render json: { top: Order.revenue_bigger_book_in_year(params[:year]).to_h, month: months }
    end

    def book_has_biggest_revenue_in_month
      render json: Order.revenue_bigger_book_in_month_of_year(params[:year], params[:month]).to_h
    end
  end
end

app/controllers/manager/charts_controller.rb
# frozen_string_literal: true

module Manager
  class ChartsController < BaseController
    include MonthConcern
    before_action :select_year, only: %i[index select_to_year]

    def index; end

    def revenue_in_year
      revenue_default = revenue_month_default
      revenue_in_year = Order.revenue_month_in_year params[:year]
      render json: revenue_default.merge(revenue_in_year)
    end

    def revenue_in_month
      revenue_default = days_in_month
      revenue_on_day = Order.revenue_day_in_month params[:month], params[:year]
      render json: revenue_default.merge(revenue_on_day)
    end

    def compare_between_year
      condition = condition_between_year params[:year_1], params[:year_2]
      result = condition.group("YEAR(created_at)").pluck("YEAR(created_at)", "SUM(total_price)")
      render json: result.to_h
    end

    def select_to_year
      year2 = @year.reject { |year| year == params[:year_1].to_i }
      render json: year2
    end

    private

    def select_year
      @year = Order.pluck(Arel.sql("DISTINCT YEAR(created_at)")).sort.reverse
    end

    def days_in_month
      @month = Settings.month[params[:month].to_sym]
      day_in_month = Time.days_in_month @month, params[:year].to_i
      day_keys_default = (1..day_in_month).map(&:to_s)
      day_values_default = day_keys_default.map { |_value| _value = 0 }
      @day_hash_default = day_keys_default.zip(day_values_default).to_h
    end

    def condition_between_year(year1, year2)
      return Order.created_between(year2, year1) if year1 >= year2

      Order.created_between(year1, year2)
    end
  end
end

app/controllers/manager/passwords_controller.rb
# frozen_string_literal: true

module Manager
  class PasswordsController < Devise::PasswordsController
    layout "session"
  end
end

app/controllers/manager/rooms_controller.rb
# frozen_string_literal: true

module Manager
  class RoomsController < BaseController
    before_action :load_room, only: :show

    def index
      @rooms = current_user.assigned_rooms.opening
    end

    def show
      respond_to do |format|
        format.js
      end
    end

    private

    def load_room
      @room = Room.find(params[:id])
    end
  end
end

app/controllers/manager/sessions_controller.rb
# frozen_string_literal: true

module Manager
  class SessionsController < Devise::SessionsController
    layout "session"
  end
end

app/views/manager/charts/index.html.slim
.container
  .row#chart_revenue
    .title-link
      = link_to t(".pdf"), "#", id: "downloadPdf", class: "btn btn-primary btn-sm"
      = link_to t(".statistical_book"), manager_chart_books_path, class: "btn btn-primary btn-sm statistical_books"
    .chart-title
        h3 = t ".revenue_the_year"
    .week-order.col-md-12
      = button_tag t(".btn"), class: "close", id: "close_revenue_the_year", aria: {label: "Close"}, data: {dismiss: "modal"}, type: "button"
      .row
        .option-year.col-md-5
          = select_tag :year, options_for_select(@year), class: "form-control order-year year_1"
        .arrow_directori.col-md-2
          = image_tag "vs.png", class: "vs-image"
        .option-year.col-md-5
          = select_tag :year, [], class: "form-control order-year year_2"
      .row.pieChart
    .chart-title
      h3 = t ".select_year"
    .week-order.col-md-12
      = button_tag t(".btn"), class: "close", id: "close_revenue_the_month_of_year", aria: {label: "Close"}, data: {dismiss: "modal"}, type: "button"
      .row
        .option-year.col-md-5
          = select_tag :year, options_for_select(@year), class: "form-control year-1"
      .row.to_day_order
    .chart-title
      h3 = t ".revenue_in_month"
    .week-order.col-md-12
      = button_tag t(".btn"), class: "close", id: "close_revenue_in_month", aria: {label: "Close"}, data: {dismiss: "modal"}, type: "button"
      .row.to_month_order